name = "CryptoPRG"
uuid = "d846c407-34c1-46cb-aa27-d51818cc05e2"
authors = ["Janis Erdmanis <janiserdmanis@protonmail.ch>"]
version = "0.1.0"

[deps]
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Nettle = "1"
Random = "1.11"
Test = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
